name: Tests CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10 test 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api.requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s . -p 'api/test.py'